env:
    es6: true
    node: true

extends:
    "eslint:recommended"

rules:
    # Allow console, debugger
    no-console: "off"
    no-debugger: "off"

    # Styles
    brace-style: ["error", "1tbs"]
    camelcase: ["error", { properties: "always" }]
    indent: ["error", 2, { SwitchCase: 1 }]
    object-curly-spacing: ["error", "always"]
    quotes: ["error", "single", { avoidEscape: true }]
    semi: ["error", "always"]
    space-before-function-paren:
        - "error"
        - { anonymous: "always", named: "never" }

    # Misc.
    eol-last: "error"
    linebreak-style: ["error", "unix"]
    no-trailing-spaces: "error"
